In [5]:
import pandas as pd
import numpy as np

In [6]:
hvc_df = pd.read_csv("../data/phase1_high_value_customer.csv")

In [7]:
hvc_df.shape

(30011, 227)

In [8]:
hvc_df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g,avg_rech_amt_6_7
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,1069.180,...,NaN,NaN,NaN,NaN,802,57.74,19.38,18.74,0.0,1185.0
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,378.721,...,NaN,1.0,1.0,NaN,315,21.03,910.65,122.16,0.0,519.0
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,492.846,...,NaN,NaN,1.0,NaN,2607,0.00,0.00,0.00,0.0,380.0
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,430.975,...,NaN,NaN,NaN,NaN,511,0.00,2.45,21.89,0.0,459.0
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,690.008,...,NaN,NaN,NaN,NaN,667,0.00,0.00,0.00,0.0,408.0

In [9]:
hvc_df.tail()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g,avg_rech_amt_6_7
30006,7001386760,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.269,...,0.0,0.0,NaN,0.0,1022,0.00,0.00,0.00,0.0,392.0
30007,7001453306,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,414.303,...,NaN,NaN,NaN,NaN,3054,0.00,0.00,0.00,0.0,465.0
30008,7001729035,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,644.973,...,1.0,1.0,1.0,1.0,2696,497.45,598.67,604.08,0.0,848.5
30009,7002111859,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,312.558,...,NaN,1.0,1.0,1.0,328,104.73,0.00,0.00,0.0,467.0
30010,7000498689,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,322.991,...,1.0,1.0,1.0,1.0,478,1445.74,1151.03,1173.18,0.0,369.5

In [10]:
hvc_df.isna().sum()

mobile_number         0
circle_id             0
loc_og_t2o_mou      114
std_og_t2o_mou      114
loc_ic_t2o_mou      114
                   ...
aug_vbc_3g            0
jul_vbc_3g            0
jun_vbc_3g            0
sep_vbc_3g            0
avg_rech_amt_6_7      0
Length: 227, dtype: int64

In [11]:
## handling the missing values, replacing the NaN with 0

cols = ['total_ic_mou_9','total_og_mou_9','vol_2g_mb_9','vol_3g_mb_9']

hvc_df[cols] = hvc_df[cols].fillna(0)

In [12]:
hvc_df[cols]

       total_ic_mou_9  total_og_mou_9  vol_2g_mb_9  vol_3g_mb_9
0                0.00            0.00         0.00         0.00
1               34.91          142.18         0.00         0.00
2              631.86          446.09         0.00         0.00
3              334.56          255.74         0.00         0.00
4               87.13          631.08         0.00         0.00
...               ...             ...          ...          ...
30006          248.88          402.71         0.00         0.00
30007           88.63          368.49         0.00         0.00
30008          547.11         1095.24         9.14       941.48
30009          265.84          182.16         0.05       393.34
30010            2.21            0.00        85.67      4177.14

[30011 rows x 4 columns]

In [13]:
## churn column creation
hvc_df['churn'] = (
    (hvc_df['total_ic_mou_9'] == 0) &
    (hvc_df['total_og_mou_9'] == 0) &
    (hvc_df['vol_2g_mb_9'] == 0) &
    (hvc_df['vol_3g_mb_9'] == 0)
).astype(int)

In [14]:
## checking the churn distribution

hvc_df['churn'].value_counts()

churn
0    27418
1     2593
Name: count, dtype: int64

In [15]:
## checking the %

hvc_df['churn'].value_counts(normalize=True) * 100

churn
0    91.359835
1     8.640165
Name: proportion, dtype: float64

In [16]:
## removing all the month 9 columns, to prevent data leakage

month9_cols = [col for col in hvc_df.columns if '_9' in col]   ##finding all the month 9 columns

hvc_df = hvc_df.drop(columns=month9_cols) ## deleting them

In [17]:
##verifying the removal

print(len(month9_cols), "columns removed")
print(hvc_df.shape)

54 columns removed
(30011, 174)

In [18]:
hvc_df['churn'].head()

0    1
1    0
2    0
3    0
4    0
Name: churn, dtype: int64

In [19]:
hvc_df.to_csv('../data/phase2_churn_label_creation.csv', index=False)